### ISSUE TITLE
Alertmanager scheme configurable 

### ISSUE THREAD

**Issue by KarineValenca** [labbsr0x/bb-promster#14]
The current configuration of bb-promster uses the same scheme of Prometheus at Alertmanager config: 

```
alerting:
  alertmanagers:
  - scheme: {{.scheme}}
    static_configs:
    - targets: ['$ALERT_MANAGER_URLS']
```

It may be necessary to change this configuration to use different schemes.
