### ISSUE TITLE
Alert templates

### ISSUE THREAD

**Issue by gutorc92** [labbsr0x/bb-promster#8]
In order to interact to telegram bot, the alertmanager rules must have an annotation app. The annotation will be used to search all subscriptions. The follow example shows how to define it:

```yml
 - alert: dependency_unresponsive
    expr: dependency_up < 1
    for: 2m
    annotations:
      app: {{$labels.prsn}}
      description: A dependência {{$labels.name}} do serviço {{$labels.prsn}} não está respondendo.
      summary: Alerta para caso uma dependência passe mais de 2 minutos sem resposta

```
